"""added roles enum

Revision ID: 0ec3a959fdae
Revises: 0f463e89dc93
Create Date: 2026-02-06 16:17:34.490508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0ec3a959fdae'
down_revision: Union[str, Sequence[str], None] = '0f463e89dc93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

role_enum = postgresql.ENUM('admin', 'user', 'guest', name='roletype')


def upgrade() -> None:
    role_enum.create(op.get_bind())
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('admin', 'user', 'guest', name='roletype'),
               existing_nullable=False,
               postgresql_using="name::roletype")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=sa.Enum('admin', 'user', 'guest', name='roletype'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
